<≤name: Gradr

apiVersion: 1

id: git101
title: Git 101
description: Git basics commands training
icon: git-alt
repository-name: git_training_101

structure:
  parts:
    - id: part_1
      title: Part 1
      description: clone, add commit & push
      max: 1
    - id: part_2
      title: Part 2
      description: Amend a commit
      max: 1
    - id: part_3
      title: Part 3
      description: Fixup commits
      max: 1
    - id: part_4
      title: Part 4
      description: Move commits
      max: 1
on:
  push:
    branches:
    - main

jobs:    
  autograde:
    name: Auto-Grade Code Changes
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Your Code
      uses: actions/checkout@v2

    - name: Prepare Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Acquire Audits
      uses: actions/checkout@v2
      with: 
        repository: exam-01-practice/assignment-02-gradr-audits-js
        path: audits

    - name: Install Dependencies
      run: |
        npm install --location=global yarn
        cd audits
        yarn install

    - name: Review Challenge - 1
      run: |
        cd audits
        yarn audit-ch-1

    - name: Review Challenge - 2
      if: always()
      run: |
        cd audits
        yarn audit-ch-2

    - name: Review Challenge - 3
      if: always()
      run: |
        cd audits
        yarn audit-ch-3

    - name: Report Audits
      if: always()
      uses: exam-01-practice/jest-to-sheets@v2
      with:
        challenge: 'ch-1;ch-2;ch-3'
        lang: javascript
        server: https://api.sheetson.com/v2/sheets
        sheetid: 1Qb5Ovjy1l2UG94Cht2govguYX5fpCIgoTKPUd2ufMm4
        token: HXlur8K20ZpoB-6FNsnSUtj2kGoDqCDHDl8vZBdLtQCv9UFOVhMsM2IBwD8
        
